import os
import re
import json
import random
import time
import logging
import hashlib
from datetime import datetime
from typing import Dict, Tuple, Any, Optional, List
from langchain_community.llms import Ollama
from django.conf import settings

from ..config.llm_config import LLMConfig

from rag.rag_service import RAGService

class GeminiLLM:
    """Lightweight wrapper for Gemini API that matches the LangChain invoke interface."""
    
    def __init__(self, api_key: str, model_name: str = "gemini-2.5-flash", temperature: float = 0.7):
        self.api_key = api_key
        self.model_name = model_name
        self.temperature = temperature
        self.logger = logging.getLogger(__name__)

    def invoke(self, prompt: str) -> str:
        import requests
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"
        headers = {
            "Content-Type": "application/json"
        }
        payload = {
            "contents": [{
                "parts": [{"text": prompt}]
            }],
            "generationConfig": {
                "temperature": self.temperature
            }
        }
        self.logger.info(f"Sending prompt to Gemini API using model: {self.model_name}")
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=120)
            response.raise_for_status()
            res_json = response.json()
            
            # Extract text response from Gemini API format
            candidates = res_json.get("candidates", [])
            if candidates:
                parts = candidates[0].get("content", {}).get("parts", [])
                if parts:
                    text_content = parts[0].get("text", "")
                    return text_content
            
            self.logger.error(f"Invalid Gemini response format: {res_json}")
            raise ValueError("No content generated by Gemini")
        except Exception as e:
            self.logger.error(f"Error calling Gemini API: {str(e)}")
            raise e

class LLMService:
    """Service untuk menghasilkan pertanyaan latihan Java melalui Ollama atau Gemini LLM."""
    
    def __init__(self, 
                 model_name: str = None, 
                 base_url: str = None):
        """
        Inisialisasi LLMService.
        
        Args:
            model_name: Nama model Ollama yang digunakan
            base_url: URL endpoint Ollama
        """
        self.config = LLMConfig()
        
        # Load configuration from LLMConfig if not provided
        self.model_name = model_name or self.config.OLLAMA_MODEL
        self.base_url = base_url or self.config.OLLAMA_BASE_URL
        self.temperature = self.config.OLLAMA_TEMPERATURE
        
        # Setup logging
        self.logger = logging.getLogger(__name__)
        self.logger.info(f"LLMService initialized. Gemini active: {self.config.USE_GEMINI}")

        self.rag_service = RAGService()
        self.successful_examples = []
        self.history_model = None
    
    def _get_history_model(self):
        """Lazy load history model to avoid circular imports"""
        if self.history_model is None:
            try:
                from ..models.generation_history import GenerationHistoryModel
                self.history_model = GenerationHistoryModel()
            except ImportError:
                self.logger.warning("GenerationHistoryModel not available, history won't be saved")
                self.history_model = None
        return self.history_model
    
    def get_llm_instance(self) -> Any:
        """
        Membuat dan mengembalikan instance LLM dengan konfigurasi yang tepat.
        Mendukung Gemini API secara default atau Ollama sebagai fallback.
        
        Returns:
            Instance GeminiLLM atau Ollama
        """
        if self.config.USE_GEMINI:
            self.logger.info(f"Menggunakan Gemini LLM: {self.config.GEMINI_MODEL}")
            return GeminiLLM(
                api_key=self.config.GEMINI_API_KEY,
                model_name=self.config.GEMINI_MODEL,
                temperature=self.config.GEMINI_TEMPERATURE
            )
        else:
            self.logger.info(f"Menggunakan Ollama LLM: {self.model_name}")
            return Ollama(
                model=self.model_name,
                base_url=self.base_url,
                temperature=self.temperature,
            )

    
    def _format_rag_context_for_prompt(self, topic: str, content: str) -> str:
        """
        Memformat konteks RAG untuk disertakan dalam prompt LLM.
        
        Args:
            topic: Topik pemrograman Java
            content: Konten materi pembelajaran
        
        Returns:
            String berisi contoh-contoh relevan dalam format yang siap dimasukkan ke prompt
        """
        if not self.rag_service.is_available():
            self.logger.warning("RAG Service tidak tersedia, tidak bisa mendapatkan contoh relevan")
            return ""
        
        try:
            self.logger.info(f"Mencari contoh RAG yang relevan untuk topik '{topic}' dengan konteks tambahan")

            # Ekstrak konsep penting dari content jika tersedia
            context = ""
            if content and len(content) > 0:
                # Ambil beberapa kalimat pertama dari materi
                sentences = content.split('.')[:3]
                context = '. '.join(sentences)[:200]
                self.logger.debug(f"Konteks tambahan: {context[:50]}...")

            examples = self.rag_service.get_relevant_examples(topic, context, n=2)

            if not examples:
                self.logger.info(f"Tidak ditemukan contoh RAG yang relevan untuk topik '{topic}'. "
                           f"Sistem akan menggunakan prompt_llm dan materi pembelajaran saja.")
                examples = self.rag_service.create_fallback_examples(topic)
            
            # Format contoh untuk prompt
            examples_text = "\n\nCONTOH SOAL LAINNYA YANG RELEVAN:\n"
            
            for i, example in enumerate(examples, 1):
                self.logger.debug(f"Contoh RAG #{i}: {example.get('studi_kasus', '')[:50]}...")
                examples_text += f"\nContoh {i}:\n"
                examples_text += f"**Studi Kasus:**\n{example.get('studi_kasus', '')}\n\n"
                examples_text += f"**Tugas:**\n{example.get('tugas', '')}\n\n"
                examples_text += f"```java\n{example.get('code', '')}\n```\n"
            
            self.logger.info(f"Berhasil mendapatkan {len(examples)} contoh RAG yang relevan")
            return examples_text
            
        except Exception as e:
            self.logger.warning(f"Error saat mendapatkan contoh RAG: {str(e)}", exc_info=True)
            return ""
    
    def create_prompt(self, prompt_llm: str, content_text: str = "", task_type: str = None) -> str:
        """
        Menyusun prompt lengkap untuk LLM dengan menambahkan instruksi dan skenario acak.
        
        Args:
            prompt_llm: Prompt dasar dari model pelajaran
            content_text: Teks materi pembelajaran
            task_type: Judul materi/topik dari database
            
        Returns:
            Prompt yang lengkap untuk dikirim ke LLM
        """
        
        timestamp = time.time()
        
        # Tambahkan materi pembelajaran jika tersedia
        max_content_length = 6000
        content_truncated = content_text
        if content_text and len(content_text) > max_content_length:
            content_truncated = content_text[:max_content_length] + "... [materi dipotong]"
            self.logger.info(f"Materi dipotong dari {len(content_text)} menjadi {max_content_length} karakter")

        # Ekstrak preview konten untuk RAG
        content_preview = ""
        if content_text and len(content_text) > 0:
            content_preview = content_text[:200]
        
        # Ambil contoh RAG yang relevan dengan topik DAN preview konten
        rag_examples = self._format_rag_context_for_prompt(task_type, content_preview)
        
        content_section = ""
        if content_truncated and len(content_truncated.strip()) > 0:
            content_section = f"""
            MATERI PEMBELAJARAN (WAJIB DIJADIKAN REFERENSI SOAL):
            {content_truncated.strip()}
            
            """
        
        # Buat instruksi yang berbeda berdasarkan ketersediaan RAG examples
        instruction_text = """
            You are an expert Java programming instructor with experience in creating programming exercises. Create a new and original Java exercise appropriate for beginner students by following these guidelines. ALL RESPONSES MUST BE IN INDONESIAN language.

            THE EXERCISE MUST BE DIRECTLY BASED ON THE LEARNING MATERIAL PROVIDED ABOVE.

            IMPORTANT! Make sure your exercise includes a clear case study and tasks. Your response format MUST EXACTLY follow this example without any additional text:

            **Studi Kasus:**
            [Deskripsi singkat konteks masalah dalam 2-3 kalimat bahasa Indonesia]

            **Tugas:**
            - [Tugas pertama yang harus dilengkapi]
            - [Tugas kedua yang harus dilengkapi]
            - [Tugas ketiga yang harus dilengkapi (jika ada)]

            ```java
            // Kode dengan bagian yang harus dilengkapi ditandai dengan komentar dan ... atau // Tulis kode di sini
            ```

            MANDATORY RULES:
            1. Case Study: Provide a short and clear description in Indonesian, maximum 3 sentences.
            2. Tasks: Provide 2-4 specific tasks in bullet points format (starting with "-") in Indonesian.
            3. Code template: Provide incomplete Java code with "..." for parts that need to be filled.
            4. ALL TEXT MUST BE IN INDONESIAN, including comments in the code.
            5. DO NOT provide answers, solutions, or complete code in the template.
            6. Do not add text or explanations outside the specified format.
            7. Ensure the Java code is syntactically valid if filled correctly.
            8. IMPORTANT: The exercise MUST handle dynamic input using `java.util.Scanner`. Use `System.in` for all user inputs.
            9. Always include `import java.util.Scanner;` in the code template and initialize the Scanner object in the `main` method.
            10. BRACES AND FORMATTING: Make sure all opening `{` and closing `}` braces are matching, perfectly balanced, and properly indented. Do not place any closing braces outside the ```java ... ``` block. The main class and all methods must be fully self-contained inside the code block.

            CHARACTERISTICS OF GOOD EXERCISES:
            - Tasks must be clear and specific (example: "Deklarasikan variabel X dengan tipe data yang sesuai")
            - Code template provides a basic structure but has parts that need to be completed
            - Parts that need to be completed are marked with "..." or "// Tulis kode di sini"
            - Exercise has appropriate difficulty level for beginner students
            - The problem is simple but has educational value
            - Code includes helpful, clean comments in Indonesian
            - Ensure beautiful and standard indentation (use 4 spaces per indent level)
            """
        
        if rag_examples:
            final_instruction = instruction_text + rag_examples + """
            
            IMPORTANT:
            ANALYZE the examples provided above carefully.
            CREATE A NEW EXERCISE THAT FOLLOWS THE SAME STRUCTURE, COMPLEXITY, AND STYLE AS THE EXAMPLES ABOVE.
            
            - Ensure the "Code Template" uses `java.util.Scanner` for all dynamic values.
            - MIMIC the complexity level of the examples above.
            
            ENSURE YOU FOLLOW THE FORMAT EXACTLY AND DO NOT ADD TEXT OUTSIDE THE FORMAT. REMEMBER: ALL OUTPUT MUST BE IN INDONESIAN LANGUAGE.
            """
        else:
            final_instruction = instruction_text + """
            
            GUIDELINES FOR CREATING EXERCISE FROM LEARNING MATERIAL:
            - Identify key programming concepts from the material (variables, methods, loops, conditionals, etc.)
            - Create a practical scenario that uses these concepts.
            - Use `java.util.Scanner` to get dynamic input for the calculations.
            
            CREATE AN EXERCISE THAT DIRECTLY APPLIES THE CONCEPTS FROM THE LEARNING MATERIAL. ENSURE YOU FOLLOW THE FORMAT EXACTLY AND DO NOT ADD TEXT OUTSIDE THE FORMAT. REMEMBER: ALL OUTPUT MUST BE IN INDONESIAN LANGUAGE.
            """

        return f"""
        {prompt_llm}
        Topic: {task_type}
        Timestamp: {timestamp} 

        {content_section}
        {final_instruction}
        """
    
    def _validate_response(self, result: Dict[str, str]) -> bool:
        """Validates the quality of the generated response."""
        # Check for minimum content length
        if len(result.get("studi_kasus", "")) < 30:
            return False
            
        # Check that code contains expected placeholders
        if "..." not in result.get("code", ""):
            return False
            
        # Check that tasks are in bullet point format
        if not re.search(r"- .+", result.get("tugas", "")):
            return False
            
        return True

    def generate_question_with_tests(self, content_id: int) -> Tuple[Dict[str, Any], float, int]:
        """
        Generate pertanyaan lengkap dengan test cases dan kode JUnit
        
        Args:
            content_id: ID konten pembelajaran
              
        Returns:
            Tuple berisi hasil, waktu generasi, dan history ID
        """
        start_time = time.time()
        
        try:
            self.logger.info(f"===== MEMULAI GENERASI PERTANYAAN DENGAN TESTS (ID: {content_id}) =====")
            
            # Mendapatkan prompt dari model content dengan lazy import
            self.logger.info(f"[1/5] Mengambil prompt_llm dan konten dari database (content_id: {content_id})")
            
            # Lazy import to avoid AppRegistryNotReady error
            from ..models.content import ContentModel
            content_model = ContentModel()
            result = content_model.get_prompt_and_description(content_id)
            
            if not result:
                self.logger.error(f"Content tidak ditemukan untuk content_id: {content_id}")
                raise ValueError(f"Content tidak ditemukan untuk content_id: {content_id}")
            
            prompt_llm = result.get('prompt_llm') or ''
            content_text = result.get('description') or ''
            content_title = result.get('title') or ''

            # Log panjang konten untuk debugging
            self.logger.info(f"Panjang prompt_llm: {len(prompt_llm)} karakter")
            self.logger.info(f"Panjang content_text: {len(content_text)} karakter")
            self.logger.info(f"Judul materi: {content_title}")
            
            # Ekstrak task_type dari konten daripada memilih secara acak
            self.logger.info(f"[2/5] Menggunakan judul materi sebagai task_type: '{content_title}'")
            self.logger.info(f"[3/5] Menyusun prompt lengkap dengan RAG examples dan materi pembelajaran")
            full_prompt = self.create_prompt(prompt_llm, content_text, content_title)
            self.logger.info(f"Prompt lengkap berhasil dibuat: {len(full_prompt)} karakter")
            
            # Mendapatkan instance LLM
            self.logger.info(f"[4/5] Mengirim prompt ke model LLM {self.model_name}")
            llm = self.get_llm_instance()
            
            llm_start_time = time.time()
            response = llm.invoke(full_prompt)
            llm_generation_time = time.time() - llm_start_time
            
            self.logger.info(f"LLM response dalam {llm_generation_time:.2f} detik")
            
            
            basic_result = self._parse_response(response)
            
            # [5/5] Generate IO Test Cases (No JUnit)
            self.logger.info("[5/5] Generating IO test cases with LLM")
            test_cases = self._generate_test_cases(basic_result)
            
            # Set empty junit code
            junit_code = ""
            
            # Gabungkan hasil lengkap
            complete_result = {
                **basic_result,
                "test_cases": test_cases,
                "junit_test_code": junit_code,
                "solution_template": basic_result.get('code', ''),
                "metadata": {
                    'content_id': content_id,
                    'content_title': content_title,
                    'generation_time': llm_generation_time,
                    'refactored': False,  
                    'junit_approach': 'io_based_grading',  # Updated to IO based grading
                    'prompting_strategy': 'io_test_generation'
                }
            }
            
            generation_time = time.time() - start_time
            
            # Simpan ke history
            history_id = 0
            try:
                history_model = self._get_history_model()
                if history_model:
                    history_id = history_model.save_generation(
                        content_id=content_id,
                        topic_title=content_title,
                        result=complete_result,
                        generation_time=generation_time
                    )
                    self.logger.info(f"History saved with ID: {history_id}")
                else:
                    self.logger.warning("History model not available, skipping history save")
            except Exception as e:
                self.logger.error(f"Error saving history: {e}")
            
            self.logger.info(f"===== GENERASI SELESAI dalam {generation_time:.2f}s =====")
            return complete_result, generation_time, history_id
            
        except Exception as e:
            execution_time = time.time() - start_time
            self.logger.error(f"Error generating question: {str(e)}", exc_info=True)
            
            # Return fallback result
            error_result = self._create_fallback_complete_result(str(e))
            return error_result, execution_time, 0
        
    # def generate_question_only(self, content_id: int) -> Dict[str, Any]:
    #     """
    #     ⚠️  LEGACY/FALLBACK FUNCTION - DEPRECATED
        
    #     Generate question only without saving files - untuk preview di admin form
        
    #     RECOMMENDATION: Use generate_question_with_tests_django() for production
    #     This function is kept for backwards compatibility and emergency fallback.
        
    #     Args:
    #         content_id: ID konten pembelajaran
              
    #     Returns:
    #         Dictionary berisi hasil generasi soal (no history tracking)
    #     """
    #     start_time = time.time()
        
    #     try:
    #         self.logger.info(f"===== GENERASI QUESTION ONLY (ID: {content_id}) =====")
            
    #         # Get content from database
    #         from ..models.content import ContentModel
    #         content_model = ContentModel()
    #         result = content_model.get_prompt_and_description(content_id)
            
    #         if not result:
    #             self.logger.error(f"Content tidak ditemukan untuk content_id: {content_id}")
    #             raise ValueError(f"Content tidak ditemukan untuk content_id: {content_id}")
            
    #         prompt_llm = result.get('prompt_llm', '')
    #         content_text = result.get('description', '')
    #         content_title = result.get('title', '')

    #         self.logger.info(f"Generating question for: {content_title}")
            
    #         # Create full prompt
    #         full_prompt = self.create_prompt(prompt_llm, content_text, content_title)
            
    #         # Get LLM instance
    #         llm = self.get_llm_instance()
            
    #         # Generate response
    #         llm_start_time = time.time()
    #         response = llm.invoke(full_prompt)
    #         llm_generation_time = time.time() - llm_start_time
            
    #         self.logger.info(f"LLM response dalam {llm_generation_time:.2f} detik")
            
    #         # Parse response
    #         basic_result = self._parse_response(response)
            
    #         # Generate test cases dan JUnit (tanpa refactoring)
    #         self.logger.info("Generating test cases dan JUnit tests dengan LLM prompt...")
    #         test_cases = self._generate_test_cases(basic_result)
    #         junit_code = self._generate_junit_tests(basic_result, test_cases)
            
    #         # Extract class name dari code
    #         class_name = self._extract_class_name(basic_result.get('code', ''))
    #         if not class_name:
    #             class_name = "GeneratedCode"
            
    #         # Combine results
    #         complete_result = {
    #             **basic_result,
    #             "test_cases": test_cases,
    #             "junit_test_code": junit_code,
    #             "solution_template": basic_result.get('code', ''),
    #             "class_name": class_name,
    #             "generation_time": llm_generation_time,
    #             "content_id": content_id,
    #             "content_title": content_title
    #         }
            
    #         generation_time = time.time() - start_time
    #         complete_result["total_generation_time"] = generation_time
            
    #         self.logger.info(f"===== QUESTION GENERATION SELESAI dalam {generation_time:.2f}s =====")
    #         return complete_result
            
    #     except Exception as e:
    #         execution_time = time.time() - start_time
    #         self.logger.error(f"Error generating question: {str(e)}", exc_info=True)
            
        
    def generate_question_with_tests_django(self, content_id: int) -> Dict[str, Any]:
        """
        Django-compatible wrapper for generate_question_with_tests
        Returns dict instead of tuple for Django views
        """
        complete_result, generation_time, history_id = self.generate_question_with_tests(content_id)
        
        # Extract class name
        class_name = self._extract_class_name(complete_result.get('code', ''))
        if not class_name:
            class_name = "GeneratedCode"
        
        # Add additional metadata
        complete_result.update({
            "class_name": class_name,
            "generation_time": generation_time,
            "history_id": history_id,
        })
        
        self.logger.info(f"Django wrapper completed successfully")
        return complete_result
            
    def _parse_response(self, response: str) -> Dict[str, str]:
        """Parse LLM response to extract components"""
        result = {
            "raw_response": response,
            "code": "",
            "studi_kasus": "",
            "tugas": ""
        }
        
        # Extract Java code
        code_pattern = r"```java(.*?)```"
        code_matches = re.findall(code_pattern, response, re.DOTALL)
        if code_matches:
            result["code"] = code_matches[0].strip()
        
        # Extract Studi Kasus
        studi_kasus_pattern = r"\*\*Studi Kasus:\*\*(.*?)(?=\*\*Tugas:\*\*|\Z)"
        studi_kasus_matches = re.findall(studi_kasus_pattern, response, re.DOTALL)
        if studi_kasus_matches:
            result["studi_kasus"] = studi_kasus_matches[0].strip()
        
        # Extract Tugas
        tugas_pattern = r"\*\*Tugas:\*\*(.*?)(?=```|$)"
        tugas_matches = re.findall(tugas_pattern, response, re.DOTALL)
        if tugas_matches:
            result["tugas"] = tugas_matches[0].strip()

        return result

    def _generate_test_cases(self, basic_result: Dict[str, str]) -> list:
        """Generate IO test cases based on the problem description and code"""
        try:
            self.logger.info("Generating IO test cases using LLM...")
            
            code = basic_result.get("code", "")
            studi_kasus = basic_result.get("studi_kasus", "")
            tugas = basic_result.get("tugas", "")
            
            prompt = f"""
            You are a QA Engineer creating test cases for a Java program.
            
            **Case Study:**
            {studi_kasus}
            
            **Student Task:**
            {tugas}
            
            **Code Structure:**
            ```java
            {code}
            ```
            
            Generate 1 simple test case to verify the program runs.
            
            Return ONLY a valid JSON array of objects with these fields:
            - `input`: MUST BE EMPTY STRING ""
            - `expected_output`: "Output" (Generic placeholder, we only check for successful execution)
            - `description`: "Verify program runs successfully without error"
            
            JSON Format Example:
            [
                {"input": "", "expected_output": "Output", "description": "Verify program runs successfully"}
            ]
            
            STRICTLY RETURN JSON ARRAY ONLY. NO MARKDOWN.
            """
            
            llm = self.get_llm_instance()
            response = llm.invoke(prompt)
            
            # Clean response to ensure valid JSON
            json_str = response.strip()
            if "```json" in json_str:
                json_str = json_str.split("```json")[1].split("```")[0].strip()
            elif "```" in json_str:
                json_str = json_str.split("```")[1].split("```")[0].strip()
                
            import json
            test_cases = json.loads(json_str)
            self.logger.info(f"Generated {len(test_cases)} Static test cases")
            return test_cases
            
        except Exception as e:
            self.logger.error(f"Error generating IO test cases: {str(e)}")
            # Fallback test cases
            return [
                {
                    "input": "0",
                    "expected_output": "Output", 
                    "description": "Basic execution test"
                }
            ]

    def _generate_junit_tests(self, basic_result: Dict[str, str], test_cases: list) -> str:
        """Generate JUnit test code menggunakan LLM prompt"""
        try:
            self.logger.info("🧪 Generating JUnit tests using LLM prompt...")
            
            code = basic_result.get("code", "")
            studi_kasus = basic_result.get("studi_kasus", "")
            tugas = basic_result.get("tugas", "")
            
            # Extract class name
            class_match = re.search(r'class\s+(\w+)', code)
            class_name = class_match.group(1) if class_match else "Solution"
            
            # Create JUnit generation prompt using FEW-SHOT strategy
            junit_prompt = self._get_junit_prompt(code, studi_kasus, tugas, class_name, test_cases)
            
            # Generate JUnit using LLM
            llm = self.get_llm_instance()
            
            llm_start_time = time.time()
            response = llm.invoke(junit_prompt)
            llm_generation_time = time.time() - llm_start_time
            
            self.logger.info(f"JUnit LLM response dalam {llm_generation_time:.2f} detik")
            
            # Parse dan validate response
            junit_code = self._parse_junit_response(response, class_name)
            
            self.logger.info("✅ JUnit test berhasil dihasilkan dengan LLM")
            return junit_code
            
        except Exception as e:
            self.logger.error(f"Error generating JUnit tests with LLM: {str(e)}")
            # Fallback to simple template if LLM fails
            return self._generate_fallback_junit_template(class_name)
    
    # Removed _create_junit_prompt (zero-shot) - now using few-shot only
    
    def _create_junit_prompt_few_shot(self, code: str, studi_kasus: str, tugas: str, class_name: str, test_cases: list) -> str:
        """Create prompt with few-shot examples for JUnit generation"""
        
        test_cases_text = ""
        for i, tc in enumerate(test_cases, 1):
            test_cases_text += f"\nTEST CASE {i}:\n"
            test_cases_text += f"Input: {tc.get('input', 'None')}\n"
            test_cases_text += f"Expected Output: {tc.get('expected', '')}\n"

        prompt = f"""
            Anda adalah pakar unit testing Java. Buatlah class JUnit 4 untuk menguji kode Java siswa berikut:
            
            KODE SISWA (TEMPLATE):
            ```java
            {code}
            ```

            STUDI KASUS: {studi_kasus}
            TUGAS: {tugas}
            CLASS NAME: {class_name}

            STRUKTUR KODE JUNIT YANG WAJIB DIIKUTI:
            ```java
            package {{{{user_package}}}};

            import static org.junit.Assert.*;
            import org.junit.Test;
            import org.junit.Before;
            import org.junit.After;
            import java.io.*;

            public class JUnit{class_name}Test {{
                
                private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
                private final PrintStream originalOut = System.out;
                private final InputStream originalIn = System.in;

                @Before
                public void setUpStreams() {{
                    System.setOut(new PrintStream(outContent));
                }}

                @After
                public void restoreStreams() {{
                    System.setOut(originalOut);
                    System.setIn(originalIn);
                }}

                // Implementasikan test cases berikut:
                {test_cases_text}

                @Test
                public void testCase1() {{
                    // Contoh simulasi input:
                    // String input = "data";
                    // System.setIn(new ByteArrayInputStream(input.getBytes()));
                    
                    // Eksekusi:
                    // {class_name}.main(null);
                    
                    // Verifikasi:
                    // String output = outContent.toString().strip();
                    // assertTrue(output.contains("expected"));
                }}
            }}
            ```

            ATURAN KHUSUS:
            1. Package HARUS `package {{{{user_package}}}};`
            2. Nama Class HARUS `JUnit{class_name}Test`.
            3. Jika soal menggunakan Scanner, ANDA WAJIB melakukan simulasi input menggunakan `System.setIn`.
            4. Gunakan asersi yang informatif dalam bahasa Indonesia.
            5. JANGAN menulis penjelasan atau teks apapun di luar blok kode Java.
            6. Pastikan setiap `AssertionError` memberikan pesan yang jelas (cth: "Output harus mengandung hasil perhitungan yang benar").
        """
        return prompt

    def _get_junit_prompt(self, code: str, studi_kasus: str, tugas: str, class_name: str, test_cases: list) -> str:
        """Get JUnit prompt using FEW-SHOT learning strategy"""
        
        self.logger.info("🎯 Using FEW-SHOT prompting strategy for JUnit generation")
        return self._create_junit_prompt_few_shot(code, studi_kasus, tugas, class_name, test_cases)

    def _parse_junit_response(self, response: str, class_name: str) -> str:
        """Parse and validate LLM response for JUnit code"""
        try:
            # Extract Java code from response if wrapped in markdown
            junit_code = response
            
            # Remove markdown code blocks if present
            if "```java" in junit_code:
                junit_code = junit_code.split("```java")[1].split("```")[0].strip()
            elif "```" in junit_code:
                junit_code = junit_code.split("```")[1].split("```")[0].strip()
            
            # Validate that it contains expected JUnit elements
            required_elements = [
                f"class JUnit{class_name}Test",
                "@Test",
                "import org.junit",
                "package {{{{user_package}}}}"
            ]
            
            for element in required_elements:
                if element not in junit_code:
                    self.logger.warning(f"Missing required element in JUnit code: {element}")
            
            # Basic syntax validation
            if not junit_code.strip():
                raise ValueError("Empty JUnit code generated")
            
            self.logger.info("JUnit code validation passed")
            return junit_code
            
        except Exception as e:
            self.logger.error(f"Error parsing JUnit response: {str(e)}")
            # Return fallback template
            return self._generate_fallback_junit_template(class_name)

    def _generate_fallback_junit_template(self, class_name: str) -> str:
        """Generate fallback JUnit template if LLM generation fails"""
        self.logger.info("Using fallback JUnit template")
        
        return f"""package {{{{user_package}}}};

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class JUnit{class_name}Test {{

    private final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    private final PrintStream originalPrintStream = System.out;

    @Before
    public void setUpStream() {{
        System.setOut(new PrintStream(outputStream));
    }}

    @After
    public void restoreStream() {{
        System.setOut(originalPrintStream);
    }}

    @Test
    public void testProgramExecution() {{
        try {{
            {{{{user_package}}}}.{class_name}.main(null);
            
            String output = outputStream.toString().trim();
            assertTrue("Program harus menghasilkan output", !output.isEmpty());
            assertTrue("Output harus informatif", output.length() >= 3);
            
        }} catch (Exception e) {{
            fail("Program error: " + e.getMessage());
        }}
    }}
    
    @Test
    public void testMainMethodExists() {{
        try {{
            {{{{user_package}}}}.{class_name}.main(new String[]{{}});
            assertTrue("Main method dapat dijalankan tanpa error", true);
        }} catch (Exception e) {{
            fail("Main method error: " + e.getMessage());
        }}
    }}
}}"""

    # def _generate_solution_template(self, basic_result: Dict[str, str]) -> str:
    #     """Generate solution template"""
    #     return basic_result.get('code', '')
    
    def _extract_class_name(self, code: str) -> str:
        """Extract class name from Java code"""
        if not code:
            return None
            
        # Look for class declaration
        class_pattern = r'public\s+class\s+(\w+)'
        match = re.search(class_pattern, code)
        if match:
            return match.group(1)
            
        # Fallback: look for any class declaration
        class_pattern = r'class\s+(\w+)'
        match = re.search(class_pattern, code)
        if match:
            return match.group(1)
            
        return None

    def _create_fallback_complete_result(self, error_message: str) -> Dict[str, Any]:
        """Create fallback result when generation fails"""
        return {
            "studi_kasus": "Error dalam generasi soal",
            "tugas": "- Implementasikan solusi dasar",
            "code": "public class Fallback { public static void main(String[] args) { System.out.println(\"Error\"); } }",
            "test_cases": [],
            "junit_test_code": "// Error generating test",
            "solution_template": "// Error",
            "error": error_message
        }

    # def generate_dynamic_files(self, content_id: int, user_package: str = None) -> Dict[str, Any]:
    #     """
    #     Generate dynamic Java template and JUnit test files.
        
    #     Args:
    #         content_id: ID konten pelajaran
    #         user_package: Package name untuk file (optional)
            
    #     Returns:
    #         Dictionary berisi informasi file yang dibuat dan path-nya
    #     """
    #     try:
    #         self.logger.info(f"===== MEMULAI DYNAMIC FILE GENERATION (ID: {content_id}) =====")
            
    #         # Generate question dengan test cases dan junit code
    #         complete_result, generation_time, history_id = self.generate_question_with_tests(content_id)
            
    #         # Set default package name jika tidak disediakan
    #         if not user_package:
    #             user_package = f"admin_generated_{content_id}_{int(time.time())}"
            
    #         # Extract class name from generated code
    #         class_name = self._extract_class_name(complete_result.get('code', ''))
    #         if not class_name:
    #             class_name = "GeneratedClass"
            
    #         self.logger.info(f"Extracted class name: {class_name}, package: {user_package}")
            
    #         # Create master directory for this question (content_id)
    #         compiler_base_path = self._get_compiler_base_path()
    #         master_dir = os.path.join(compiler_base_path, "question_masters", f"question_{content_id}")
            
    #         # Create master directory if it doesn't exist
    #         os.makedirs(master_dir, exist_ok=True)
    #         self.logger.info(f"Creating/updating master files for question {content_id} with class {class_name}")
            
    #         # Generate master template files with placeholders
    #         java_file_path = self._create_java_template_file(
    #             complete_result, class_name, master_dir
    #         )
            
    #         # Generate JUnit test file in master directory
    #         junit_file_path = self._create_junit_test_file(
    #             complete_result, class_name, master_dir
    #         )

    #         # ✅ NEW: Copy JUnit test to test_cases directory for JavaRunner
    #         test_cases_junit_path = self._copy_junit_to_test_cases(
    #             junit_file_path, class_name, content_id
    #         )

    #         # Generate solution template
    #         solution_file_path = self._create_solution_template_file(
    #             complete_result, class_name, master_dir
    #         )
            
    #         # Create metadata file
    #         self._create_metadata_file(master_dir, class_name, content_id, complete_result)
            
    #         # Prepare return data dengan struktur yang sesuai dengan router
    #         file_generation_result = {
    #             "success": True,
    #             "data": complete_result,
    #             "files_created": {
    #                 "java_template": java_file_path,
    #                 "junit_test": junit_file_path,
    #                 "junit_test_cases": test_cases_junit_path,  # ✅ NEW: Add test_cases path
    #                 "solution_template": solution_file_path,
    #                 "question_directory": master_dir
    #             },
    #             "file_generation": {
    #                 "package_name": user_package,
    #                 "class_name": class_name,
    #                 "java_file_path": java_file_path,
    #                 "junit_file_path": junit_file_path,
    #                 "junit_test_cases_path": test_cases_junit_path,  # ✅ NEW: Add test_cases path
    #                 "solution_file_path": solution_file_path,
    #                 "package_directory": master_dir,
    #                 "generation_time": generation_time,
    #                 "history_id": history_id,
    #                 "content_id": content_id
    #             }
    #         }
            
    #         self.logger.info(f"✅ Dynamic files berhasil dibuat:")
    #         self.logger.info(f"  - Java Template: {java_file_path}")
    #         self.logger.info(f"  - JUnit Test (Master): {junit_file_path}")
    #         self.logger.info(f"  - JUnit Test (Test Cases): {test_cases_junit_path}")  # ✅ NEW
    #         self.logger.info(f"  - Solution: {solution_file_path}")
    #         self.logger.info(f"===== DYNAMIC FILE GENERATION SELESAI =====")
            
    #         return file_generation_result
            
    #     except Exception as e:
    #         self.logger.error(f"Error dalam dynamic file generation: {str(e)}", exc_info=True)
    #         return {
    #             "success": False,
    #             "error": str(e),
    #             "data": {},
    #             "files_created": {},
    #             "file_generation": {}
    #         }

    def save_junit_test_file(self, junit_code: str, class_name: str, question_id: int) -> str:
        """
        Save JUnit test file to test_cases directory after question is saved
        
        Args:
            junit_code: JUnit test code
            class_name: Java class name
            question_id: Database question ID
            
        Returns:
            Path to saved file
        """
        try:
            # Debug logging
            self.logger.info(f"🔄 Starting JUnit file save process")
            self.logger.info(f"   - Question ID: {question_id}")
            self.logger.info(f"   - Class Name: {class_name}")
            self.logger.info(f"   - JUnit Code Length: {len(junit_code)} characters")
            
            # Ensure test_cases directory exists
            test_cases_dir = os.path.join(settings.BASE_DIR, "java_files", "test_cases")
            self.logger.info(f"   - Target Directory: {test_cases_dir}")
            
            # Create directory if not exists
            if not os.path.exists(test_cases_dir):
                os.makedirs(test_cases_dir, exist_ok=True)
                self.logger.info(f"   - Created directory: {test_cases_dir}")
            else:
                self.logger.info(f"   - Directory already exists")
            
            # Create filename with question_id
            junit_filename = f"JUnit{class_name}Test_Q{question_id}.java"
            file_path = os.path.join(test_cases_dir, junit_filename)
            self.logger.info(f"   - Target File: {file_path}")
            
            # Process JUnit code for file system
            processed_junit_code = self._process_junit_code_for_file(junit_code, class_name)
            self.logger.info(f"   - Processed JUnit Code Length: {len(processed_junit_code)} characters")
            
            # Write to file
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(processed_junit_code)
            
            # Verify file was created
            if os.path.exists(file_path):
                file_size = os.path.getsize(file_path)
                self.logger.info(f"✅ JUnit test saved successfully: {file_path} ({file_size} bytes)")
            else:
                raise Exception("File was not created successfully")
                
            return file_path
            
        except Exception as e:
            self.logger.error(f"❌ Error saving JUnit test: {str(e)}")
            self.logger.error(f"   - Question ID: {question_id}")
            self.logger.error(f"   - Class Name: {class_name}")
            self.logger.error(f"   - Target Dir: {os.path.join(settings.BASE_DIR, 'java_files', 'test_cases')}")
            return None

    def _process_junit_code_for_file(self, junit_code: str, class_name: str) -> str:
        """
        Process JUnit code to ensure proper format for file system
        Enhanced with better logging and validation
        """
        try:
            import re
            
            self.logger.info(f"🔧 Processing JUnit code for file system")
            self.logger.info(f"   - Original Code Length: {len(junit_code)}")
            self.logger.info(f"   - Target Class Name: {class_name}")
            
            # Remove any existing package declaration
            original_code = junit_code
            junit_code = re.sub(r'package\s+[^;]+;', '', junit_code)
            
            if original_code != junit_code:
                self.logger.info(f"   - Removed existing package declaration")
            
            # Add package placeholder that JavaRunner expects
            processed_code = f"""package {{{{user_package}}}};

{junit_code.strip()}"""
            
            # Ensure proper class name in JUnit test
            expected_class_name = f"JUnit{class_name}Test"
            if expected_class_name not in processed_code:
                self.logger.info(f"   - Fixing class name to: {expected_class_name}")
                # Replace generic test class names with proper naming
                processed_code = re.sub(
                    r'public\s+class\s+\w*Test\s*\{',
                    f'public class {expected_class_name} {{',
                    processed_code
                )
            
            # Replace any placeholder class references
            processed_code = processed_code.replace("{{class_name}}", class_name)
            
            self.logger.info(f"   - Final Code Length: {len(processed_code)}")
            self.logger.info(f"   - Expected Class Name Present: {expected_class_name in processed_code}")
            
            return processed_code
            
        except Exception as e:
            self.logger.error(f"❌ Error processing JUnit code: {str(e)}")
            return junit_code  # Return original code as fallback
    
    def _get_compiler_base_path(self) -> str:
        """Get the base path to the online compiler directory"""
        return settings.BASE_DIR

    def _create_java_template_file(self, result: Dict[str, Any], class_name: str, 
                                 master_dir: str) -> str:
        """Create the Java template file with package placeholder"""
        try:
            java_code = result.get('code', '')
            
            # Create template with package placeholder
            template_code = f"""package {{{{USER_PACKAGE}}}};

{java_code}"""
            
            # Remove any existing package declaration
            template_code = re.sub(r'package\s+[^;]+;', '', template_code)
            template_code = f"package {{{{USER_PACKAGE}}}};\n\n{template_code.strip()}"
            
            # Write to template file
            file_path = os.path.join(master_dir, f"{class_name}_Template.java")
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(template_code)
            
            self.logger.info(f"Java template file created: {file_path}")
            return file_path
            
        except Exception as e:
            self.logger.error(f"Error creating Java template file: {str(e)}")
            raise

    def _create_junit_test_file(self, result: Dict[str, Any], class_name: str, 
                              master_dir: str) -> str:
        """Create the JUnit test file with package placeholder"""
        try:
            junit_code = result.get('junit_test_code', '')
            
            if not junit_code:
                junit_code = f"""import static org.junit.Assert.*;
import org.junit.Test;

public class JUnit{class_name}Test {{
    
    @Test
    public void testBasicExecution() {{
        try {{
            {class_name}.main(new String[]{{}});
            assertTrue("Program can run without errors", true);
        }} catch (Exception e) {{
            fail("Program failed to run: " + e.getMessage());
        }}
    }}
}}"""
            
            # Create template with package placeholder
            template_code = f"""package {{{{USER_PACKAGE}}}};

{junit_code}"""
            
            # Remove any existing package declaration
            template_code = re.sub(r'package\s+[^;]+;', '', template_code)
            template_code = f"package {{{{USER_PACKAGE}}}};\n\n{template_code.strip()}"
            
            # Replace any class name placeholders
            template_code = template_code.replace("{{user_package}}", "{{USER_PACKAGE}}")
            template_code = template_code.replace("{{class_name}}", class_name)
            
            # Write to file
            test_filename = f"JUnit{class_name}Test"
            file_path = os.path.join(master_dir, f"{test_filename}.java")
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(template_code)
            
            self.logger.info(f"JUnit test file created: {file_path}")
            return file_path
            
        except Exception as e:
            self.logger.error(f"Error creating JUnit test file: {str(e)}")
            raise

    def _create_solution_template_file(self, result: Dict[str, Any], class_name: str, 
                                     master_dir: str) -> str:
        """Create a solution template file for reference"""
        try:
            solution_code = result.get('solution_template', result.get('code', ''))
            
            template_code = f"""package {{{{USER_PACKAGE}}}};

{solution_code}"""
            
            # Remove any existing package declaration
            template_code = re.sub(r'package\s+[^;]+;', '', template_code)
            template_code = f"package {{{{USER_PACKAGE}}}};\n\n{template_code.strip()}"
            
            # Write to file
            file_path = os.path.join(master_dir, f"{class_name}_Solution.java")
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(template_code)
            
            self.logger.info(f"Solution template file created: {file_path}")
            return file_path
            
        except Exception as e:
            self.logger.error(f"Error creating solution template file: {str(e)}")
            raise

    def _create_metadata_file(self, master_dir: str, class_name: str, content_id: int, result: Dict[str, Any]) -> str:
        """Create metadata file for the master files"""
        try:
            metadata = {
                "content_id": content_id,
                "class_name": class_name,
                "created_at": datetime.now().isoformat(),
                "question_title": result.get('question', ''),
                "topic": result.get('topic', ''),
                "files": {
                    "template": f"{class_name}_Template.java",
                    "junit_test": f"JUnit{class_name}Test.java",
                    "solution": f"{class_name}_Solution.java",
                    "junit_test_cases": f"JUnit{class_name}Test_Q{content_id}.java"
                },
                "paths": {
                    "master_dir": master_dir,
                    "test_cases_dir": "../java_files/test_cases/"
                },
                "last_updated": datetime.now().isoformat()
            }
            
            metadata_path = os.path.join(master_dir, "metadata.json")
            with open(metadata_path, 'w', encoding='utf-8') as f:
                json.dump(metadata, f, indent=2, ensure_ascii=False)
            
            self.logger.info(f"Metadata file created: {metadata_path}")
            return metadata_path
            
        except Exception as e:
            self.logger.error(f"Error creating metadata file: {str(e)}")
            raise
    
    def _copy_junit_to_test_cases(self, junit_file_path: str, class_name: str, content_id: int) -> str:
        """
        Enhanced copy function dengan better error handling dan logging
        """
        try:
            compiler_base_path = self._get_compiler_base_path()
            test_cases_dir = os.path.join(compiler_base_path, "java_files", "test_cases")
            
            # Ensure test_cases directory exists
            os.makedirs(test_cases_dir, exist_ok=True)
            self.logger.info(f"📁 Test cases directory: {test_cases_dir}")
            
            # Check if source file exists
            if not os.path.exists(junit_file_path):
                self.logger.error(f"❌ Source JUnit file not found: {junit_file_path}")
                return None
            
            # Read the original JUnit file from master
            with open(junit_file_path, 'r', encoding='utf-8') as f:
                junit_content = f.read()
            
            self.logger.info(f"📖 Read JUnit file content: {len(junit_content)} characters")
            
            # Create filename with pattern expected by JavaRunner
            junit_filename = f"JUnit{class_name}Test_Q{content_id}.java"
            test_cases_file_path = os.path.join(test_cases_dir, junit_filename)
            
            # Replace package placeholder to match JavaRunner expectations
            junit_content = junit_content.replace("{{USER_PACKAGE}}", "{{user_package}}")
            
            # Write to test_cases directory
            with open(test_cases_file_path, 'w', encoding='utf-8') as f:
                f.write(junit_content)
            
            # Verify file was created
            if os.path.exists(test_cases_file_path):
                file_size = os.path.getsize(test_cases_file_path)
                self.logger.info(f"✅ JUnit test copied successfully:")
                self.logger.info(f"   📁 File: {test_cases_file_path}")
                self.logger.info(f"   📊 Size: {file_size} bytes")
                return test_cases_file_path
            else:
                self.logger.error(f"❌ File was not created successfully: {test_cases_file_path}")
                return None
                
        except Exception as e:
            self.logger.error(f"❌ Error copying JUnit test to test_cases: {str(e)}")
            return None

    # def _update_junit_filename_after_question_save(self, old_file_path: str, class_name: str, 
    #                                             content_id: int, actual_question_id: int) -> str:
    #     """
    #     Update JUnit filename after question is saved to database and we have the actual question_id
        
    #     Args:
    #         old_file_path: Current file path with content_id
    #         class_name: Java class name
    #         content_id: Original content ID
    #         actual_question_id: Actual question ID from database
        
    #     Returns:
    #         New file path with correct question_id
    #     """
    #     try:
    #         if not old_file_path or not os.path.exists(old_file_path):
    #             self.logger.warning(f"Old file path not found: {old_file_path}")
    #             return None
                
    #         # Create new filename with actual question_id
    #         compiler_base_path = self._get_compiler_base_path()
    #         test_cases_dir = os.path.join(compiler_base_path, "java_files", "test_cases")
    #         new_filename = f"JUnit{class_name}Test_Q{actual_question_id}.java"
    #         new_file_path = os.path.join(test_cases_dir, new_filename)
            
    #         # Read content from old file
    #         with open(old_file_path, 'r', encoding='utf-8') as f:
    #             content = f.read()
            
    #         # Write to new file
    #         with open(new_file_path, 'w', encoding='utf-8') as f:
    #             f.write(content)
            
    #         # Remove old file
    #         os.remove(old_file_path)
            
    #         self.logger.info(f"✅ JUnit filename updated: {old_file_path} → {new_file_path}")
    #         return new_file_path
            
    #     except Exception as e:
    #         self.logger.error(f"❌ Error updating JUnit filename: {str(e)}")
    #         return None

    def generate_question_with_tests_django(self, content_id: int) -> Dict[str, Any]:
        """
        Django-compatible wrapper for generate_question_with_tests
        Returns dict instead of tuple for Django views
        """
        complete_result, generation_time, history_id = self.generate_question_with_tests(content_id)
        
        # Extract class name
        class_name = self._extract_class_name(complete_result.get('code', ''))
        if not class_name:
            class_name = "GeneratedCode"
        
        # Add additional metadata
        complete_result.update({
            "class_name": class_name,
            "generation_time": generation_time,
            "history_id": history_id,
        })
        
        self.logger.info(f"Django wrapper completed successfully")
        return complete_result

    def grade_submission(self, student_code: str, test_results: list, question_text: str = "") -> dict:
        """
        Grade a student submission using the LLM as a judge.
        Useful when strict I/O matching fails due to formatting issues.
        
        Args:
            student_code: The Java code submitted by the student
            test_results: List of dicts {input, expected, actual, passed}
            question_text: The original question text (optional context)
            
        Returns:
            dict: { "score": int, "feedback": str, "is_correct": bool }
        """
        try:
            self.logger.info("🤖 Memulai AI Grading untuk validasi hasil eksekusi...")
            
            # Format test results for prompt
            results_text = ""
            for i, res in enumerate(test_results, 1):
                clean_actual = res.get('actual', '').strip()[:200] # Limit length
                clean_expected = res.get('expected', '').strip()[:200]
                results_text += f"\nTEST CASE {i}:\n"
                results_text += f"Input: {res.get('input', '')}\n"
                results_text += f"Expected Output: {clean_expected}\n"
                results_text += f"Actual Output: {clean_actual}\n"
                results_text += f"Status: {'PASSED' if res.get('passed') else 'FAILED'}\n"

            prompt = f"""
            Anda adalah Asisten Pengajar Ilmu Komputer yang Teliti namun Adil.
            Tugas Anda adalah menilai kode Java siswa yang GAGAL dalam tes otomatis (Strict Match) karena masalah format atau minor.
            
            ATURAN PENILAIAN:
            1. FOKUS PADA OUTPUT. Karena input statis, output harus mencerminkan hasil perhitungan variabel hardcoded.
            2. TOLERANSI format. "Luas: 50" == "Luas = 50" == "50".
            3. LOGIKA HARUS BENAR. Jika hasil perhitungan salah, nilai 0.
            4. Jika kode menggunakan Scanner (padahal diminta Static), TAPI outputnya benar (karena sistem inject input kosong), TETAP BERI NILAI 100.
            5. Jika output siswa secara semantik BENAR sesuai maksud soal, BERI NILAI 100.

            DATA SISWA:
            Kode:
            ```java
            {student_code[:1000]}
            ```

            HASIL EKSEKUSI:
            {results_text}

            PERTANYAAN:
            Apakah kode siswa ini SEBENARNYA BENAR secara logika meskipun format outputnya sedikit berbeda?
            
            JAWAB HANYA DALAM JSON:
            {{
                "score": <0 atau 100>,
                "feedback": "<Penjelasan singkat max 2 kalimat bahasa Indonesia>",
                "is_correct": <true/false>
            }}
            """
            
            llm = self.get_llm_instance()
            response = llm.invoke(prompt)
            
            # Parse JSON
            import json
            import re
            
            content = response.content if hasattr(response, 'content') else str(response)
            match = re.search(r'\{.*\}', content, re.DOTALL)
            if match:
                json_str = match.group(0)
                result = json.loads(json_str)
                self.logger.info(f"✅ AI Grading Result: {result}")
                return result
            else:
                self.logger.warning("Gagal parse output JSON AI Grading")
                return {"score": 0, "feedback": "Gagal menilai otomatis.", "is_correct": False}
                
        except Exception as e:
            self.logger.error(f"Error AI Grading: {str(e)}")
            return {"score": 0, "feedback": "Error sistem penilaian AI.", "is_correct": False}